### ISSUE TITLE
Combine modules?

### ISSUE THREAD

**Issue by proychou** [greninger-lab/covid_swift_pipeline#10]
(this is just for the iupac-edit branch) 
Can we just have a single process to do the pileup and pipe into ivar since we're not really using the pileup output for anything else here? 
https://github.com/greninger-lab/covid_swift_pipeline/blob/10505bde4531d7e913d7a003df3ed845e5c42844/modules.nf#L2

**Comment by asereewit** [comment]
Combined pileup generation and calling consensus using ivar
