### ISSUE TITLE
Mapped reads for bwa-mem

### ISSUE THREAD

**Issue by proychou** [greninger-lab/covid_swift_pipeline#7]
Looks like we're outputting NA for mapped reads after mapping with bwa-mem. Possible to include count of mapped reads?

https://github.com/greninger-lab/covid_swift_pipeline/blob/76b331e2e7f214206bcbe0386a9871bf942fe15c/modules.nf#L165

**Comment by asereewit** [comment]
Added mapped reads calculation and tested on 2 covid samples using artic_v4.1.
