### ISSUE TITLE
Add trimming for new QIAseq primers

### ISSUE THREAD

**Issue by proychou** [greninger-lab/covid_swift_pipeline#9]
QIAGEN released boosters to improve coverage with Omicron: https://www.qiagen.com/us/resources/resourcedetail?id=d98e01ad-4c27-483a-b473-74dcd3d9cadf&lang=en

Need to add support for this in trimming step as a new option under --PRIMERS

**Comment by asereewit** [comment]
Added QIAseq booster primerset. Please use --PRIMERS QIASEQ_BOOSTER.
